Repository typo3-trainer-network/books, pull requests merged in 2019-12, with the labels that each got.

#30 [TASK] Create all Extbase-relevant folders
  CHANGELOG.md
  Classes/Controller/.gitkeep
  Classes/Domain/Model/.gitkeep
  Classes/Domain/Repository/.gitkeep
  Classes/ViewHelpers/.gitkeep
  Configuration/FlexForms/.gitkeep
  Configuration/TCA/Overrides/.gitkeep
  Configuration/TSconfig/Page/.gitkeep
  Configuration/TSconfig/User/.gitkeep
  Configuration/TypoScript/.gitkeep
  Resources/Private/Language/.gitkeep
  Resources/Private/Layouts/.gitkeep
  Resources/Private/Partials/.gitkeep
  Resources/Private/Templates/.gitkeep
  Resources/Public/CSS/.gitkeep
  Resources/Public/Icons/.gitkeep
  Resources/Public/Images/.gitkeep
  Resources/Public/JavaScript/.gitkeep
  Tests/Functional/.gitkeep
  Tests/Unit/.gitkeep
Labels: enhancement

#31 [TASK] Add the basic extension files
  .gitignore
  CHANGELOG.md
  Resources/Public/Icons/.gitkeep
  Resources/Public/Icons/Extension.svg
  composer.json
  ext_emconf.php
Labels: enhancement

#32 [FEATURE] Lint the PHP files via GitHub actions
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: enhancement

#33 [FEATURE] Add a Composer script for PHP linting
  .github/workflows/ci.yml
  CHANGELOG.md
  composer.json
Labels: enhancement

#36 [CLEANUP] Drop an empty class from the SVG
  Resources/Public/Icons/Extension.svg
Labels: cleanup

#37 [FEATURE] Add status badges to the README
  CHANGELOG.md
  README.md
Labels: documentation, enhancement

#35 [TASK] Document the licensing in the README
  CHANGELOG.md
  README.md
Labels: documentation

#39 [FEATURE] Create a "hello world" plugin without templating
  CHANGELOG.md
  Classes/Controller/.gitkeep
  Classes/Controller/HelloWorldController.php
  Configuration/TCA/Overrides/.gitkeep
  Configuration/TCA/Overrides/tt_content.php
  ext_localconf.php
Labels: enhancement

#41 [CLEANUP] Fix a PSR-12 style violation
  Classes/Controller/HelloWorldController.php
Labels: cleanup

#38 [TASK] Add TS linting and PHP code sniffing
  .github/workflows/ci.yml
  CHANGELOG.md
  Configuration/TsLint.yml
  composer.json
  phpcs.xml.dist
Labels: enhancement

#42 [FEATURE] Create a "hello world" plugin with templating
  CHANGELOG.md
  Classes/Controller/HelloWorldController.php
  Configuration/TCA/Overrides/sys_template.php
  Configuration/TCA/Overrides/tt_content.php
  Configuration/TypoScript/.gitkeep
  Configuration/TypoScript/constants.typoscript
  Configuration/TypoScript/setup.typoscript
  README.md
  Resources/Private/Layouts/.gitkeep
  Resources/Private/Layouts/Default.html
  Resources/Private/Templates/HelloWorld/GreetWithTemplate.html
  ext_localconf.php
Labels: enhancement
